# frozen_string_literal: true

module AubergineMachine
  module MemoryMap
    RAM_START = 0x0000
    RAM_END = 0x7EFF

    ZERO_PAGE_START = 0x0000
    ZERO_PAGE_END = 0x00FF

    STACK_START = 0x0100
    STACK_END = 0x01FF

    SHELL_SCRATCH_START = 0x00F0
    SHELL_SCRATCH_END = 0x00FF

    COMMAND_BUFFER_START = 0x0200
    COMMAND_BUFFER_SIZE = 0x40
    COMMAND_BUFFER_END = COMMAND_BUFFER_START + COMMAND_BUFFER_SIZE - 1

    EDITOR_PATH_BUFFER_START = 0x0240
    EDITOR_PATH_BUFFER_SIZE = 0x40
    EDITOR_PATH_BUFFER_END = EDITOR_PATH_BUFFER_START + EDITOR_PATH_BUFFER_SIZE - 1

    EDITOR_COMMAND_BUFFER_START = 0x0280
    EDITOR_COMMAND_BUFFER_SIZE = 0x20
    EDITOR_COMMAND_BUFFER_END = EDITOR_COMMAND_BUFFER_START + EDITOR_COMMAND_BUFFER_SIZE - 1

    EDITOR_YANK_BUFFER_START = 0x02A0
    EDITOR_YANK_BUFFER_SIZE = 0x40
    EDITOR_YANK_BUFFER_END = EDITOR_YANK_BUFFER_START + EDITOR_YANK_BUFFER_SIZE - 1

    EDITOR_UNDO_BUFFER_START = 0x02E0
    EDITOR_UNDO_BUFFER_SIZE = 0x80
    EDITOR_UNDO_BUFFER_END = EDITOR_UNDO_BUFFER_START + EDITOR_UNDO_BUFFER_SIZE - 1

    EDITOR_UNDO_META_START = 0x0360
    EDITOR_UNDO_META_SIZE = 0x05
    EDITOR_UNDO_META_END = EDITOR_UNDO_META_START + EDITOR_UNDO_META_SIZE - 1

    EDITOR_SEARCH_BUFFER_START = 0x0368
    EDITOR_SEARCH_BUFFER_SIZE = 0x20
    EDITOR_SEARCH_BUFFER_END = EDITOR_SEARCH_BUFFER_START + EDITOR_SEARCH_BUFFER_SIZE - 1

    EDITOR_SEARCH_LENGTH_ADDRESS = 0x0388
    EDITOR_SEARCH_DIRECTION_ADDRESS = 0x0389
    EDITOR_ACTIVE_ADDRESS = 0x038A

    LOAD_BUFFER_START = 0x0400
    LOAD_BUFFER_SIZE = 0x80
    LOAD_BUFFER_END = LOAD_BUFFER_START + LOAD_BUFFER_SIZE - 1

    TERMINAL_START = 0x7F00
    TERMINAL_END = 0x7F04
    FILESYSTEM_START = 0x7F10
    FILESYSTEM_END = 0x7FDF
    ROM_START = 0x8000
    ROM_END = 0xFFFF
  end
end
